import { Link } from "react-router-dom";

export default function Features() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute -left-40 top-10 h-96 w-96 rounded-full bg-violet-200/40 blur-3xl" />

        <div className="absolute -right-40 top-10 h-96 w-96 rounded-full bg-indigo-200/40 blur-3xl" />

        <div className="relative mx-auto max-w-7xl px-6 py-20">
          <div className="mx-auto max-w-3xl text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white px-4 py-2 text-sm font-medium text-violet-600 shadow-sm">
              <span>✦</span>
              Powerful Interview Features
            </div>

            <h1 className="text-5xl font-extrabold leading-tight tracking-tight md:text-6xl">
              Everything You Need to
              <span className="block bg-linear-to-r from-violet-600 to-indigo-600 bg-clip-text text-transparent">
                Prepare Better
              </span>
            </h1>

            <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">
              AI Interview Agent combines intelligent questioning,
              conversational interviews, answer evaluation, and actionable
              feedback into one simple platform.
            </p>
          </div>
        </div>
      </section>

      {/* Main Features */}
      <section className="mx-auto max-w-7xl px-6 pb-20">
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <FeatureCard
            icon="🤖"
            title="AI-Powered Interview"
            description="Practice with an AI interviewer that conducts a conversational technical interview instead of simply displaying a list of questions."
          />

          <FeatureCard
            icon="🧠"
            title="Context-Aware Questions"
            description="Questions can be generated around the candidate's skills, background, curriculum, and interview context."
          />

          <FeatureCard
            icon="💬"
            title="Conversational Flow"
            description="The interview maintains context across multiple responses so the conversation feels more natural and realistic."
          />

          <FeatureCard
            icon="📊"
            title="Answer Evaluation"
            description="Your responses are analyzed to understand your technical knowledge and identify areas where you need improvement."
          />

          <FeatureCard
            icon="🎯"
            title="Personalized Interview"
            description="The interview experience can adapt to the candidate instead of giving everyone exactly the same questions."
          />

          <FeatureCard
            icon="📝"
            title="Detailed Feedback"
            description="Receive a structured summary containing your strengths, knowledge gaps, and recommended next steps."
          />

          <FeatureCard
            icon="🔄"
            title="Session-Based Interviews"
            description="Every interview maintains its own session so the AI can remember the conversation throughout the interview."
          />

          <FeatureCard
            icon="📚"
            title="RAG-Based Knowledge"
            description="Relevant information can be retrieved from your knowledge base to make interview questions more meaningful and contextual."
          />

          <FeatureCard
            icon="⚡"
            title="Fast AI Responses"
            description="Get responses quickly and keep the interview moving without unnecessary interruptions."
          />
        </div>
      </section>

      {/* Interview Flow */}
      <section className="bg-white py-20">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mx-auto max-w-2xl text-center">
            <p className="text-sm font-bold uppercase tracking-widest text-violet-600">
              How Features Work Together
            </p>

            <h2 className="mt-3 text-3xl font-bold md:text-4xl">
              From first question to final feedback
            </h2>

            <p className="mt-4 leading-7 text-slate-600">
              The platform combines multiple features into one continuous
              interview experience.
            </p>
          </div>

          <div className="mt-12 grid gap-6 md:grid-cols-4">
            <FlowCard
              number="01"
              title="Start"
              text="Enter your candidate ID and begin the interview."
            />

            <FlowCard
              number="02"
              title="Interview"
              text="Answer technical questions generated by the AI."
            />

            <FlowCard
              number="03"
              title="Evaluate"
              text="The AI analyzes your answers and interview performance."
            />

            <FlowCard
              number="04"
              title="Improve"
              text="Receive feedback and actionable next steps."
            />
          </div>
        </div>
      </section>

      {/* Feedback Features */}
      <section className="mx-auto max-w-7xl px-6 py-20">
        <div className="overflow-hidden rounded-3xl bg-linear-to-r from-violet-600 to-indigo-600 p-8 text-white shadow-2xl shadow-violet-200 md:p-12">
          <div className="grid items-center gap-10 lg:grid-cols-2">
            <div>
              <p className="text-sm font-semibold uppercase tracking-widest text-violet-200">
                Smart Feedback
              </p>

              <h2 className="mt-3 text-3xl font-bold md:text-4xl">
                Know what to improve next.
              </h2>

              <p className="mt-5 max-w-xl leading-7 text-violet-100">
                After the interview, the system provides structured feedback
                so you can understand your performance instead of simply
                receiving a score.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <FeedbackItem
                title="Summary"
                text="Overall performance overview"
              />

              <FeedbackItem
                title="Strengths"
                text="Topics you performed well in"
              />

              <FeedbackItem
                title="Gaps"
                text="Areas that need more practice"
              />

              <FeedbackItem
                title="Next Steps"
                text="Actionable recommendations"
              />
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-slate-200 bg-slate-50 py-20">
        <div className="mx-auto max-w-3xl px-6 text-center">
          <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-100 text-3xl">
            🚀
          </div>

          <h2 className="mt-6 text-3xl font-bold md:text-4xl">
            Ready to test your skills?
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            Put your knowledge to the test with an AI-powered technical
            interview.
          </p>

          <Link
            to="/"
            className="mt-8 inline-flex rounded-xl bg-linear-to-r from-violet-600 to-indigo-600 px-7 py-3.5 text-sm font-bold text-white shadow-lg shadow-violet-200 transition hover:from-violet-700 hover:to-indigo-700"
          >
            Start Interview →
          </Link>
        </div>
      </section>
    </div>
  );
}


/* Feature Card */

function FeatureCard({ icon, title, description }) {
  return (
    <div className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-violet-200 hover:shadow-xl">
      <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-violet-100 text-2xl transition group-hover:bg-violet-600">
        {icon}
      </div>

      <h3 className="mt-5 text-xl font-bold text-slate-900">
        {title}
      </h3>

      <p className="mt-3 text-sm leading-7 text-slate-600">
        {description}
      </p>
    </div>
  );
}


/* Interview Flow Card */

function FlowCard({ number, title, text }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-slate-50 p-6 transition hover:-translate-y-1 hover:border-violet-200 hover:shadow-lg">
      <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-violet-600 text-sm font-bold text-white">
        {number}
      </div>

      <h3 className="mt-5 text-lg font-bold">{title}</h3>

      <p className="mt-2 text-sm leading-6 text-slate-600">
        {text}
      </p>
    </div>
  );
}


/* Feedback Item */

function FeedbackItem({ title, text }) {
  return (
    <div className="rounded-2xl border border-white/20 bg-white/10 p-5 backdrop-blur-sm">
      <h3 className="font-bold">{title}</h3>

      <p className="mt-2 text-sm leading-6 text-violet-100">
        {text}
      </p>
    </div>
  );
}